name: Publish dspyteach (TestPyPI)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Optional Git ref or tag to publish"
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_tag || github.ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"

      - name: Build distributions
        run: uv build --no-sources
        working-directory: dspy-file

      - name: Publish to TestPyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
        run: uv publish --index testpypi dist/*
        working-directory: dspy-file
